const ACCION_EDITAR_PROGRAMAS_LISTA = 'editar';
const ACCION_CREAR_PROGRAMAS_LISTA = 'crear';

export default {
  ACCION_EDITAR_PROGRAMAS_LISTA: ACCION_EDITAR_PROGRAMAS_LISTA,
  ACCION_CREAR_PROGRAMAS_LISTA: ACCION_CREAR_PROGRAMAS_LISTA,
}
