const CARPETA_BASE_PROGRAMA_IMAGES = 'facultad/ingenieria/programas/{{snies}}-{{name_programa}}/images';
const CARPETA_BASE_PROGRAMA_DOCUMENTOS = 'facultad/ingenieria/programas/{{snies}}-{{name_programa}}/documentos';
const CARPETA_BASE_PROFESOR_FOTO_PERFIL = 'facultad/ingenieria/profesores/{{login}}-{{userId}}/images/profile';
const CARPETA_BASE_NOTICIA_FOTO_PERFIL = 'facultad/ingenieria/noticias/{{noticiaId}}/images';
const CARPETA_BASE_EVENTO_FOTO_PERFIL = 'facultad/ingenieria/eventos/{{eventoId}}/images';
const CARPETA_BASE_SEMILLERO_FOTO_PERFIL = 'facultad/ingenieria/semilleros/{{semilleroId}}/images';
const TIPOS_IMAGEN_PERMITIDOS = ['image/png', 'image/jpeg', 'image/jpg'];
const TIPOS_DOCUMENTOS_PERMITIDOS = ['application/pdf'];
const TAMANO_MAXIMO_ARCHIVOS = 15728640;

export default {
  CARPETA_BASE_PROGRAMA_IMAGES: CARPETA_BASE_PROGRAMA_IMAGES,
  CARPETA_BASE_PROGRAMA_DOCUMENTOS: CARPETA_BASE_PROGRAMA_DOCUMENTOS,
  CARPETA_BASE_PROFESOR_FOTO_PERFIL: CARPETA_BASE_PROFESOR_FOTO_PERFIL,
  CARPETA_BASE_NOTICIA_FOTO_PERFIL: CARPETA_BASE_NOTICIA_FOTO_PERFIL,
  CARPETA_BASE_EVENTO_FOTO_PERFIL: CARPETA_BASE_EVENTO_FOTO_PERFIL,
  CARPETA_BASE_SEMILLERO_FOTO_PERFIL: CARPETA_BASE_SEMILLERO_FOTO_PERFIL,
  TIPOS_IMAGEN_PERMITIDOS: TIPOS_IMAGEN_PERMITIDOS,
  TIPOS_DOCUMENTOS_PERMITIDOS: TIPOS_DOCUMENTOS_PERMITIDOS,
  TAMANO_MAXIMO_ARCHIVOS: TAMANO_MAXIMO_ARCHIVOS,
}
