const IDENTIFICADOR_TIPO_PROGRAMA = 'TIPSGRMA';
const IDENTIFICADOR_TIPO_FORMACION = 'TIPSFRMN';
const IDENTIFICADOR_TIPO_RED_SOCIAL = 'TIPRDSCAL';
const IDENTIFICADOR_TIPO_DOCUEMNTO_IMAGE = 'TIPDOCIMG';
const IDENTIFICADOR_TIPO_DOCUEMNTO_IMAGE_NUMBER = 5;
const IDENTIFICADOR_TIPO_DOCUEMNTO_DOCUMENTO_NUMBER = 6;
const IDENTIFICADOR_TIPO_DOCUEMNTO_PLAN_ESTUDIO_NUMBER = 7;

export default {
  IDENTIFICADOR_TIPO_PROGRAMA: IDENTIFICADOR_TIPO_PROGRAMA,
  IDENTIFICADOR_TIPO_FORMACION: IDENTIFICADOR_TIPO_FORMACION,
  IDENTIFICADOR_TIPO_RED_SOCIAL: IDENTIFICADOR_TIPO_RED_SOCIAL,
  IDENTIFICADOR_TIPO_DOCUEMNTO_IMAGE: IDENTIFICADOR_TIPO_DOCUEMNTO_IMAGE,
  IDENTIFICADOR_TIPO_DOCUEMNTO_IMAGE_NUMBER: IDENTIFICADOR_TIPO_DOCUEMNTO_IMAGE_NUMBER,
  IDENTIFICADOR_TIPO_DOCUEMNTO_DOCUMENTO_NUMBER: IDENTIFICADOR_TIPO_DOCUEMNTO_DOCUMENTO_NUMBER,
  IDENTIFICADOR_TIPO_DOCUEMNTO_PLAN_ESTUDIO_NUMBER: IDENTIFICADOR_TIPO_DOCUEMNTO_PLAN_ESTUDIO_NUMBER,
}
