const IDENTIFICADOR_TIPO_PROGRAMA = 'TIPSGRMA';
const IDENTIFICADOR_TIPO_FORMACION = 'TIPSFRMN';
const IDENTIFICADOR_TIPO_RED_SOCIAL = 'TIPRDSCAL';
const IDENTIFICADOR_TIPO_DOCUEMNTO_IMAGE = 'TIPDOCIMG';
const IDENTIFICADOR_TIPO_PROFESOR = 'TIPPFR';
const IDENTIFICADOR_TIPO_TITULO_ACADEMICO = 'TIPTLSACDS';
const IDENTIFICADOR_TIPO_LABORATORIO = 'TIPLABS';
const IDENTIFICADOR_TIPO_NIVEL_ACADEMICO = 'TIPNVADMC';
const IDENTIFICADOR_TIPO_DOCUEMNTO_IMAGE_NUMBER = 5;
const IDENTIFICADOR_TIPO_DOCUEMNTO_DOCUMENTO_NUMBER = 6;
const IDENTIFICADOR_TIPO_DOCUEMNTO_PLAN_ESTUDIO_NUMBER = 7;
const IDENTIFICADOR_TIPO_DOCUEMNTO_MICRO_DISENO_NUMBER = 8;
const IDENTIFICADOR_ID_ESTADO_HUILA_COLOMBIA = 19;
const IDENTIFICADOR_ID_TIPO_LABORATORIO_GRANJA = 23;
const IDENTIFICADOR_ID_TIPO_LABORATORIO_MUSEO = 24;

export default {
  IDENTIFICADOR_TIPO_PROGRAMA: IDENTIFICADOR_TIPO_PROGRAMA,
  IDENTIFICADOR_TIPO_FORMACION: IDENTIFICADOR_TIPO_FORMACION,
  IDENTIFICADOR_TIPO_RED_SOCIAL: IDENTIFICADOR_TIPO_RED_SOCIAL,
  IDENTIFICADOR_TIPO_DOCUEMNTO_IMAGE: IDENTIFICADOR_TIPO_DOCUEMNTO_IMAGE,
  IDENTIFICADOR_TIPO_PROFESOR: IDENTIFICADOR_TIPO_PROFESOR,
  IDENTIFICADOR_TIPO_NIVEL_ACADEMICO: IDENTIFICADOR_TIPO_NIVEL_ACADEMICO,
  IDENTIFICADOR_TIPO_TITULO_ACADEMICO: IDENTIFICADOR_TIPO_TITULO_ACADEMICO,
  IDENTIFICADOR_TIPO_DOCUEMNTO_IMAGE_NUMBER: IDENTIFICADOR_TIPO_DOCUEMNTO_IMAGE_NUMBER,
  IDENTIFICADOR_TIPO_DOCUEMNTO_DOCUMENTO_NUMBER: IDENTIFICADOR_TIPO_DOCUEMNTO_DOCUMENTO_NUMBER,
  IDENTIFICADOR_TIPO_DOCUEMNTO_PLAN_ESTUDIO_NUMBER: IDENTIFICADOR_TIPO_DOCUEMNTO_PLAN_ESTUDIO_NUMBER,
  IDENTIFICADOR_TIPO_DOCUEMNTO_MICRO_DISENO_NUMBER: IDENTIFICADOR_TIPO_DOCUEMNTO_MICRO_DISENO_NUMBER,
  IDENTIFICADOR_ID_ESTADO_HUILA_COLOMBIA: IDENTIFICADOR_ID_ESTADO_HUILA_COLOMBIA,
  IDENTIFICADOR_TIPO_LABORATORIO: IDENTIFICADOR_TIPO_LABORATORIO,
  IDENTIFICADOR_ID_TIPO_LABORATORIO_GRANJA: IDENTIFICADOR_ID_TIPO_LABORATORIO_GRANJA,
  IDENTIFICADOR_ID_TIPO_LABORATORIO_MUSEO: IDENTIFICADOR_ID_TIPO_LABORATORIO_MUSEO,
}
