const IDENTIFICADOR_TIPO_PROGRAMA = 'TIPSGRMA';
const IDENTIFICADOR_TIPO_FORMACION = 'TIPSFRMN';

export default {
  IDENTIFICADOR_TIPO_PROGRAMA: IDENTIFICADOR_TIPO_PROGRAMA,
  IDENTIFICADOR_TIPO_FORMACION: IDENTIFICADOR_TIPO_FORMACION,
}
